### PR TITLE
README Updates

### PR DESCRIPTION
**Pull request by jrobinsonkrm**
* Updated README with examples of starting all 5 supported setups
* Added removeVistaSource.sh to cover required post install requirements
* Updated rpms and vxvista post installer to use removeVistaSource.sh
* Added entry build arg to adjust for when running Cache

### CODE REVIEW

**Review by ChristopherEdwards — APPROVED** [review]

**Comment by shabiel** [comment]
Joe,

Give me some time. I am working with George Lilly now.

**Comment by shabiel** [comment]
I tried one yesterday, and it failed like this: Error processing tar
file(exit status 1): write /home/osehra/Dashboard/VistA-M/Packages/Lexicon
Utility/Globals/757.033-3+CHARACTER POSITIONS.zwr: no space left on device

I haven't seen this before. Any hints?

--Sam

**Comment by shabiel** [comment]
Googled it. Common problem on Macs apparently. Trying again now.

**Comment by ChristopherEdwards** [comment]
@shabiel the docker machine is probably out of space (macs use a virtual machine to provide a docker environment either through HyperKit or VirtualBox) delete some old images/containers and it should free up some space.

**Comment by shabiel** [comment]
@josephsnyder Did you see these failures before in the Tests?

https://code.osehra.org/CDash/viewTest.php?onlyfailed&buildid=38397

**Comment by shabiel** [comment]
Okay. It didn't work. It builds fine; but something to do with the entry
point not being defined:

docker run -p 9431:9431 -p 8002:8002 -p 2223:22 -p 8080:8080 -d -P
--name=osehravista osehra-vista
saichiko:docker-vista sam$ docker ps -a
CONTAINER ID        IMAGE                 COMMAND
CREATED                  STATUS
PORTS
NAMES
e0f8e36cd2b9        osehra-vista          "/bin/sh -c ${entry_…"   Less
than a second ago   Exited (126) 3 minutes
ago
osehravista

What am I doing wrong?

**Comment by jrobinsonkrm** [comment]
@shabiel I'm looking into this right now.  Will have an update for you shortly

**Comment by shabiel** [comment]
+1 for being communicative!

**Comment by jrobinsonkrm** [comment]
@shabiel @ChristopherEdwards 
I just ran the build and it looks like YottaDB is failing:
```
Downloading ydbinstall
Something went wrong downloading ydbinstall
Creating osehra...
ls: cannot access /opt/yottadb/: No such file or directory
ls: cannot access /opt/yottadb/: No such file or directory
ls: cannot access /opt/yottadb/: No such file or directory
```

The `Something went wrong downloading ydbinstall` is from GTM/install.sh:92.  I may need help troubleshooting that since the YottaDB sections were updated just after I updated the Dockerfile.

**Comment by ChristopherEdwards** [comment]
This is due to the SHA hash updating of the ydbinstall script (due to changes i made there :) ). please remove the line that does the SHA hashing I think i'm being too careful. The only thing i'd do is make sure the file looks like a shell script (file, sed, etc can be used to check) so that we don't try to execute an html file...

**Comment by josephsnyder** [comment]
Hi Sam,

We have seen those errors before. I don't have a good explanation as to why it happens during these "headless" runs.  I'll run a local one to be sure.

**Comment by shabiel** [comment]
@jrobinsonkrm

Update this file:

```
$ cat GTM/ydbinstall_SHA1
f563850db56e19aa3d482a595474445cf29228bb  ydbinstall
```

**Comment by ChristopherEdwards** [comment]
i have a feeling that the entry point isn't defined as it isn't looking at the dockerfile any more (hunch/guess) and since we refer to an environment variable it doesn't exist. if you run docker run --env entry=<whatever it needs to be> it *should* work.

**Comment by jrobinsonkrm** [comment]
I did a check on the entry_path variable in the dockerfile and it returned correctly:
```
Step 25/27 : RUN echo ${entry_path}
 ---> Running in edfaa10a9528
/home/osehra/bin/start.sh
```

**Comment by ChristopherEdwards** [comment]
right, because you are in the dockerfile. that may not be what sam is doing - he may be trying to re-run an image already created (thus won't run the dockerfile).

**Comment by shabiel** [comment]
I am a dummy reading the instructions: Here's what I did:

```
docker build -t osehra-vista .
docker run -p 9431:9431 -p 8002:8002 -p 2223:22 -p 8080:8080 -d -P
--name=osehravista osehra-vista
```

**Comment by ChristopherEdwards** [comment]
I don't see any updated run instructions, so that is what i would have ran. not sure that I like having the entry point using an environment variable due to this issue.

**Comment by jrobinsonkrm** [comment]
There isn't a reason for using --env entry= since that's a build arg.
`ARG entry="/home"`
`ENV entry_path="${entry}/${instance_name}/bin/start.sh"`
And since `entry` has a default you don't need to supply it.  `entry_path` will build the correct entry path dynamically (this is because cache is in a different location than GTM/YottaDB)

**Comment by ChristopherEdwards** [comment]
Apologies i misspoke about the build arg (i was just using sam's posting without going back to the code to get the exact arg name) - yes, entry_path should be the right variable to pass to the run command.

Maybe the $basedir for cache should change so it is more in-line with GT.M/YottaDB and we can avoid this whole mess from the beginning. I quickly added Caché support without much thinking and it appears I was short sighted with how I set $basedir, keeping the cache in /opt/cachesys still makes sense though - just the location of start.sh should be different.

**Comment by jrobinsonkrm** [comment]
@shabiel I have fixed the entrypoint and permission issues with the post installer script.  Can you please pull and test again

**Comment by shabiel** [comment]
Okay. I will try it now.

**Comment by shabiel** [comment]
Okay. I had a problem with a stuck CMake; but when I did it again, it worked fine.

I will test the others now and see how they go.

**Comment by shabiel** [comment]
Update:

I tried osehra vista; worldvista. Both work fine. Now trying vxvista. There is a stray password prompt near the end. Not sure what that's doing there, but it's not affecting anything that I can see.

**Comment by jrobinsonkrm** [comment]
That password prompt is the script running one of the clean up post install scripts.  You can see them here:
https://github.com/OSEHRA/docker-vista/pull/3/files#diff-e8c809c0f2fa8c0bf8d137fa12edf882R3

**Comment by shabiel** [comment]
One more bug:

Cache installer says the following:

Installation completed successfully
/opt/vista/Cache
Moving CACHE.DAT...
'/opt/vista/cache-files/CACHE.DAT' -> '/opt/cachesys/cache/vista/CACHE.DAT'
/opt/vista /opt/vista/Cache
using 'cache.cpf' configuration file

This copy of Cache has been licensed for use exclusively by:
License missing or unreadable.
Copyright (c) 1986-2015 by InterSystems Corporation
Any other use is a violation of your license agreement

Database CACHE already exists, LINE:'CACHE=/opt/cachesys/cache/vista/' at line 13
Error: Parsing CPF file /opt/cachesys/cache/cache.cpf - Shutting down the systemStarting CACHE

An error was detected during Cache startup.
** Startup aborted **
Instance is not running
/opt/vista/Cache

There's a bug in the cache.cpf file. The CACHE database is repeated.

**Comment by jrobinsonkrm** [comment]
@shabiel there is only one reference for the CACHE database in cache.cpf:
https://github.com/jrobinsonkrm/docker-vista/blob/readme-update/Cache/cache.cpf#L13

Is there a way you can get your copy of the cache.cpf so I can examine it?  Also, what steps did you take to get to this error so I can try to recreate it?

**Comment by josephsnyder** [comment]
@shabiel , did you call your instance "cache"?  I know that the script does some "find and replace" with the FOIA string to add in the instance name: https://github.com/jrobinsonkrm/docker-vista/blob/readme-update/Cache/install.sh#L124.  That would give us the duplication of that named file.

Sorry about the duplication of emails, @jrobinsonkrm

**Comment by jrobinsonkrm** [comment]
@shabiel @josephsnyder looks like the instance name was the issue.  I've updated it locally to `cachevista` but would like input on the name in case there is something better to call it.

**Review by shabiel — APPROVED** [review]

**Comment by shabiel** [comment]
A - OK.

There are some minor issues with the README which I can take care of. I am not in the office my now in front of the computer I had the changes on.

**Pull request merged**
