### PR TITLE
Add ProfileBrowserIDE support

### PR DESCRIPTION
**Pull request by ChristopherEdwards**
* Add exposed ports for tomcat and mtm
 * Add install for tomcat and derby
 * Add install for profile browser ide war
 * Configure profile browser ide to start on container startup if it exists

### CODE REVIEW

**Review by shabiel — CHANGES_REQUESTED** [review]
The YottaDB installer doesn't work anymore. Can you fix that? Naraynan made a change last week.

**Comment by ChristopherEdwards** [comment]
I was actually just testing with the updated hash :). pushed change

**Comment by shabiel** [comment]
Good.

Any reason we are staying with an older version of YottaDB?

--Sam

**Comment by ChristopherEdwards** [comment]
regarding the older version. I'll make a separate pull request that bumps the version number. I try to stay targeted with my pull requests.

**Pull request merged**
