### PR TITLE
Update PIP installation script

### PR DESCRIPTION
**Pull request by ChristopherEdwards**
* PIP build is now controlled with CMake
 * Update various scripts as the path has changed
 * Add Java JDK to installation for future PIP Browser IDE install

### CODE REVIEW

**Review by shabiel — CHANGES_REQUESTED** [review]
I couldn't get the commands right to create the docker image to test this. I want better documentation first in the README. Thanks!

**Comment by ChristopherEdwards** [comment]
Commit added with requested changes.

**Comment by shabiel** [comment]
So the readme has a small typo:

```
docker build --build-arg flags="-y -b -e -m -q -s" --build-arg instance="osehra" --build-arg postInstallScript="-p ./Common/pvPostInstall.sh" -t osehrapip .
```
pvPostInstall is actually a Cache thing. It works well w/o the post install:

```
docker build --build-arg flags="-y -b -e -m -q -s" --build-arg instance="osehra" -t osehrapip .
```

Mapping has issues:
```
OSEHRA>D MAPFM^KBBOSQL(200)
%GTM-E-UNDEF, Undefined local variable: QUIT
		At M source location CREATEMAP+19^KBBOSQL
```
Tried to fix that, and then move on:

```
OSEHRA>D MAPFM^KBBOSQL(200)
%GTM-E-UNDEF, Undefined local variable: PARENT
		At M source location GETPARENTS+1^KBBOSQL
```

Since I got multiple errors, I thought I would stop and let you see.

**Comment by ChristopherEdwards** [comment]
Sam:

you must use pip/dm to map files. I've pushed changes to the README to make this clear. I was able to recreate your error when i used mumps -dir, but as soon as I used the pip/dm script everything ran as intended.

**Review by shabiel — APPROVED** [review]

**Pull request merged**
