### PR TITLE
Fix name of downloaded PIP folder

### PR DESCRIPTION
**Pull request by josephsnyder**
Update the name of the PIP folder that is downloaded from

   https://github.com/YottaDB/PIP/archive/master.zip

### CODE REVIEW

**Comment by shabiel** [comment]
What am I checking for Joe? Why would the rename matter?

**Comment by josephsnyder** [comment]
The rename of the folder is required since we build and copy things out of it in the changed lines above.  It threw a bunch of errors when I was trying to build the OSEHRA VistA update this morning.

**Review by ChristopherEdwards — APPROVED** [review]

**Comment by ChristopherEdwards** [comment]
Yes, YottaDB changed the repo name thus the downloaded zip will have a new folder name. I forgot about this when we renamed the repos.

**Comment by shabiel** [comment]
Testing now.

**Pull request merged**
