### PR TITLE
Add support for installing Octo and YottaDB from source

### PR DESCRIPTION
**Pull request by ChristopherEdwards**
Update various files to support installing Octo instead of PIP.
Also remove references to PIP.

### CODE REVIEW

**Comment by shabiel** [comment]
I tested Cache today on this PR branch.

**Comment by josephsnyder** [comment]
I built the default Octo setup following your instructions and the build seemed to go quite smoothly.  The only request I have is to make sure to talk about the SquirrelSQL hang and fix somewhere in the documentation, as I am still experiencing it:
> Workaround for SquirrelSQL Hang:
> ssh -p 2223 root@localhost # password: docker
> su - vehu
> mumps -dir
> kill ^%ydboctoschema("PG_CATALOG.PG_ATTRDEF")

By that same logic, we don't give them any information on how to connect so maybe it can be left out.

**Comment by ChristopherEdwards** [comment]
Hmm I thought I killed that node so that it would be "fixed" I'll double check and add more documentation on how to connect with SquirrelSQL as well.

**Comment by josephsnyder** [comment]
Thanks Christopher!

Whether you our I killed it, it is gone in my test instance.  However, SquirrelSQL still hangs when I type in a table name.

**Comment by ChristopherEdwards** [comment]
@josephsnyder are you saying that it is still hanging even after you killed the global?

I did look and it appears I don't kill the global in this MR, will be fixed along with the documentation in the next update.

**Comment by josephsnyder** [comment]
Hi again,

I just spun up a new container from the built image.  It doesn't seem to have the ^%ydboctoschema("PG_CATALOG.PG_ATTRDEF") because I cannot zwrite it to the screen after building the image.  I am still hanging when trying to write (not execute) a SQL query in SQuirreL, I've attached my rocto.log file.  There are a few errors in it, but they seem to ping about features not yet implemented
[rocto.log](https://github.com/OSEHRA/docker-vista/files/3402938/rocto.log)

**Comment by ChristopherEdwards** [comment]
Looking into it.

**Comment by ChristopherEdwards** [comment]
@josephsnyder Octo has improved and the workaround for SquirrelSQL isn't needed anymore and should perform as expected. I've updated it to the latest master as well.

**Review by josephsnyder — APPROVED** [review]
Using the default commands for building and running, I was able to get SQuirrel SQL connected to the Octo instance and query the running instance. Looks good to me!

**Comment by shabiel** [comment]
Wow Joe! You found time to do this!

So, it's good to merge in my opinion. Next time we do docker images
(perhaps for VEHU), we should add that in.

--Sam

**Comment by shabiel** [comment]
I was looking at the PR, and since we are changing the version of
YottaDB, and the YottaDB installer, I need to do a few more tests
before merging.

--Sam

**Review by shabiel — APPROVED** [review]

**Pull request merged**
