### PR TITLE
Clean up docker install

### PR DESCRIPTION
**Pull request by ChristopherEdwards**

### CODE REVIEW

**Comment by ChristopherEdwards** [comment]
This is still a work in progress. Just giving the early review/look at things as i'm working on them.

**Comment by shabiel** [comment]
Can you update the Readme instructions?

**Comment by ChristopherEdwards** [comment]
I'm not close to done. Readme, testing, UTF-8, and other clean up are still todos

**Comment by shabiel** [comment]
Okay.

**Review by shabiel — APPROVED** [review]
Looks good.

**Comment by shabiel** [comment]
The changes look good; I won't merge until the docs are updated as well.
Thank you so much for your work!

**Comment by ChristopherEdwards** [comment]
@shabiel @josephsnyder this should be good for review now.

**Comment by shabiel** [comment]
I am having trouble right now with my machine not finishing the curl
download when I need to test. So a bit pissed off right now--I tried
it like 5 times. The curl download finishes on my Mac though.

So I will try testing this later.

**Comment by shabiel** [comment]
I got an error in installing vxVistA:

```
docker build --build-arg flags="-y -b -s -a https://github.com/OSEHRA/vxVistA-M/archive/master.zip -p ./Common/vxvistaPostInstall.sh" --build-arg instance="vxvista" -t vxvista .
```

unzip:  cannot find or open virgin_install.zip, virgin_install.zip.zip or virgin_install.zip.ZIP.

Do you want to take a look or should I?

**Comment by ChristopherEdwards** [comment]
@shabiel it should be fixed now.

**Comment by shabiel** [comment]
Thank you so much. I am testing again now.

--Sam

**Review by shabiel — APPROVED** [review]

**Pull request merged**
